### ISSUE TITLE
Predentation not working with h4 elements

### ISSUE THREAD

**Issue by oleersoy** [daleeidd/predentation#1]
Hello,

Thank you for making predentation.  It's exactlly what I need.  

I'm running into a strange issue.  I've create a gulp task that uses `predentation`.  It first does some syntax highlighting, then uses predentation to remove the white space inside the pre tag.  The repository containing the task is here:

[superfly-css-task-test](https://github.com/superfly-css/superfly-css-task-test)

If I run the task on the following text, [contained in the repository](https://github.com/superfly-css/superfly-css-task-test/blob/master/src/test/html/index.html):

``` html
    <pre class="Test-markup">
      <code class="html">
        <div class="Grid">
          <div class="Grid-cell">1/2</div>
          <div class="Grid-cell">2/2</div>
        </div>
      </code>
    </pre>
```

I get the expected result (Syntax highlighted):

``` html
    <pre class="Test-markup">
      <code class="html">
&lt;<span class="hljs-keyword">div</span> <span class="hljs-type">class</span>=<span class="hljs-string">&quot;Grid&quot;</span>&gt;
  &lt;<span class="hljs-keyword">div</span> <span class="hljs-type">class</span>=<span class="hljs-string">&quot;Grid-cell&quot;</span>&gt;<span class="hljs-number">1</span>/<span class="hljs-number">2</span>&lt;/<span class="hljs-keyword">div</span>&gt;
  &lt;<span class="hljs-keyword">div</span> <span class="hljs-type">class</span>=<span class="hljs-string">&quot;Grid-cell&quot;</span>&gt;<span class="hljs-number">2</span>/<span class="hljs-number">2</span>&lt;/<span class="hljs-keyword">div</span>&gt;
&lt;/<span class="hljs-keyword">div</span>&gt;
      </code>
    </pre>

```

However it does not work on this content:

``` html
        <h4>u-color-background-gray-100</h4>
        <div class="u-color-background-gray-100 transparent-test-block">
        </div>
        <h4>u-color-background-gray-300</h4>
        <div class="u-color-background-gray-300 transparent-test-block">
```

If I remove the first h4 element it works.  Thoughts?

TIA,
Ole

**Comment by oleersoy** [comment]
One more observation.  If I run predentation before the highlighting it also does nothing.  So in other words if I try to run predentation on this content nothing happens:

``` html
    <pre class="Test-markup">
      <code class="html">
        <div class="Grid">
          <div class="Grid-cell">1/2</div>
          <div class="Grid-cell">2/2</div>
        </div>
      </code>
    </pre>
``
```

**Comment by magenta404** [comment]
It was a poorly thought out regular expression on my part. I will push a fix out soon.

**Comment by oleersoy** [comment]
Wow - that was fast.  Seems to be working great now :+1: !  Thanks - Brilliant work!
